name: Retest Check

on:
  push:

jobs:
  retest-steps:
    runs-on: ubuntu-latest

    steps:
      - name: run some command
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 5
          retry_on: error
          max_attempts: 2
          run: |
            echo "hello retry"
            exit 1